services:
    Google\Client:
        class: Google\Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['%env(GOOGLE_CLIENT_ID)%']]
            - [setClientSecret, ['%env(GOOGLE_CLIENT_SECRET)%']]
            - [setAuthConfig, ['%env(resolve:GOOGLE_AUTH_CONFIG)%']]
