security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(?:_(profiler|wdt)|_error)
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleOAuthAuthenticator
                - App\Security\FacebookOAuthAuthenticator

            entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/auth/google, roles: PUBLIC_ACCESS }
        - { path: ^/auth/facebook, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }